on:
  push: { }

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3 ]
        laravel: [ 8.*, 9.*, 10.*, 11.* ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 8.*
            php: 7.4
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, iconv
          coverage: none
      - run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - run: |
          vendor/bin/phpunit
